---
title: Quick guide to setting up OBS studio
author: Jason Winget
date: '2019-01-27'
slug: quick-guide-to-setting-up-obs-studio
categories:
  - Screencasts
tags: []
image:
  caption: ''
  focal_point: ''
---

I got a little bit of interest in yesterday's screencast for #TidyTuesday, so today I thought I'd give a simple guide to recording those screencasts with OBS studio.

The text instructions are below and here's a short video if you're a visual learner.

<iframe width="853" height="480" src="https://www.youtube.com/embed/OihrGzv3d2g" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


1. [Download and install](https://obsproject.com) the software
2. In the lower left of the window under `scenes`, click `+` and create a new scene called `screencasts`
3. Under `sources`, click `+` and add a `Display Capture`. Make sure you can see the monitor you want to capture in the preview.
4. (Optional) Click `+` in `sources` again and add a `Video Capture Device` to include your webcam. The video window can be resized and moved with the mouse.
5. Do a mic test and make sure you see audio levels in the `mixer`. If not, click the gear and select/set up the microphone
6. Press `Start Recording` and go for it!

The videos will go to your default video folder (C:/Users/username/Videos on Win10).